name: Deploy Frontend

on:
  push:
    branch: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.fe
          push: true
          tags: rajatsdev/docker-turbo-fe:${{ github.sha }}
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}

      # - name: Deploy to VM
      #   env:
      #     COMPUTE_HOST: ${{ secrets.COMPUTE_HOST }}
      #     COMPUTE_USERNAME: ${{ secrets.COMPUTE_USERNAME }}
      #     SSH_PRIVATE_KEY: ${{ secrets.COMPUTE_SSH_KEY }}
      #   run: |
      #     echo "$SSH_PRIVATE_KEY" > private_key.pem
      #     chmod 700 private_key.pem
      #     ssh -o StrictHostKeyChecking=no -i private_key.pem ${COMPUTE_USERNAME}@${COMPUTE_HOST} -t "docker stop turbo-fe && docker run --name turbo-fe -d -p 8081:8081 rajatsdev/docker-turbo-fe:${{ github.sha }}"
