name: Deploy Server

on:
  push:
    branch: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.se
          push: true
          tags: rajatsdev/docker-turbo-server:${{ github.sha }}

      - name: Deploy to VM
        env:
          COMPUTE_HOST: ${{ secrets.COMPUTE_HOST }}
          COMPUTE_USERNAME: ${{ secrets.COMPUTE_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.COMPUTE_SSH_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 700 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${COMPUTE_USERNAME}@${COMPUTE_HOST} -t "\
          docker stop turbo-server || true && \
          docker rm turbo-server || true && \
          docker run -d --name turbo-server -p 8000:8000 -e DATABASE_URL='"$DATABASE_URL"' rajatsdev/docker-turbo-server:${{ github.sha }}"
